### ISSUE TITLE
RENAME table_attestation_ball TO table_attestation_Scores

### ISSUE THREAD

**Issue by JoeFreedom** [itstep-vrn/University#12]
Предложение переименовать `table_attestation_ball` в `table_attestation_scores`

Change row `ball` to `scores`

**Comment by anst-foto** [comment]
@SergeyOlisov  @RenataRobertovna 
Нужна ваша резолюция

**Comment by SergeyOlisov** [comment]
Согласен. В таком случае предлагаю так же переименовать `table_ball ` в `table_score`

**Comment by anst-foto** [comment]
Закрыто коммитом https://github.com/itstep-vrn/University/commit/66e54cc95cdb1bf3f26dfaf627e6c30dccd1f744

**Comment by SergeyOlisov** [comment]
Переоткрываю. Продублирую - предлагаю так же переименовать `table_ball` в `table_score`

**Comment by anst-foto** [comment]
Закрываю на основе создания #15
