### ISSUE TITLE
Row and Table renaming

### ISSUE THREAD

**Issue by JoeFreedom** [itstep-vrn/University#19]
| Tables                    | NAME              | REPLACE               |
|---------------------------|-------------------|-----------------------|
| table_address             | house             | building              |
|                           |                   |                       |
|table_grant	            | table_grant	    | table_scholarship     |
|table_grant	            | type			    | scholarship_type      |
|table_grant	            | appointment_date	| start_date            |
|table_grant	            | expiration_date	| end_date              |
|table_grant	            | grand_amount	    | scholarship_amount    |
|                           |                   |                       |
|table_phone		        | type			    | phone_type            |
|table_phone		        | phone		        | phone_number          |
|                           |                   |                       |
|table_score		        | ball		        | mark                  |
|                           |                   |                       |
|table_subject_work_program | number_of_hours	| hours_of_study        |
|                           |                   |                       |
|table_subject		        | number_of_hours	| hours_of_study        |

**Comment by SergeySamodurovS** [comment]
Done
