### ISSUE TITLE
Наполнение таблиц данными

### ISSUE THREAD

**Issue by anst-foto** [itstep-vrn/University#21]
В каждой таблице должно быть не менее 10 записей (смотрите по таблице)

**Меленчук** - `table_phone`, `table_student`, `table_subject`, `table_teacher`
**Лев** - `table_mark`, `table_person`, `table_grant`, `table_subject_work_program`
**Алексей Алексеевич** - ` table_group`, `table_specialty`
**Рената** - `table_email`, `table_faculty`
**Джоел** - `table_attestation_type`, `table_contacts`
**Самодуров** - `table_attestation_form`, `table_attestation_mark`
**Яков** - `table_address`, `able_attestation_from_subject`

**Comment by RenataRobertovna** [comment]
Я беру таблицу `table_specialty` у @alekseyxpavlov,  а тебе отдаю `table_email`.

**Comment by JoeFreedom** [comment]
не смог заполнить table_contacts нужен заполненые данные из других таблиц через id

**Comment by XMelexus** [comment]
Все таблицы заполнены
