### ISSUE TITLE
Проблемы с table_teacher

### ISSUE THREAD

**Issue by XMelexus** [itstep-vrn/University#5]
![issue](https://user-images.githubusercontent.com/58857939/100129778-068e6e80-2e93-11eb-8b7d-87ecba34cd87.png)
 

1.  `table_teacher` связан с `table_student`, а это значит, что учитель не может быть создан без создания такого-же студента, даже если он не нужен.

2. Поля `id_address`, `id_email`, `id_phone` не нужны, так как они уже связаны с `table_teacher` (подробнее на пикче)

**Comment by SergeySamodurovS** [comment]
Исправлено
